### ISSUE TITLE
Theming the newly maintained FreeCAD master PieMenu addon 

### ISSUE THREAD

**Issue by luzpaz** [MisterMakerNL/ExtremeProDark#4]
User @mdkus has taken over maintainership of PieMenu. The new repo is at https://github.com/mdkus/PieMenu

@MisterMakerNL are you in to keeping this on your radar where your theme is compatible with PieMenu development ?

**Comment by MisterMakerNL** [comment]
Looks to work pretty good only some small bugs:
https://github.com/mdkus/PieMenu/issues/7

**Comment by luzpaz** [comment]
Thanks mate!
