### ISSUE TITLE
Unreadable spreadsheets

### ISSUE THREAD

**Issue by Kreyren** [MisterMakerNL/ExtremeProDark#5]
The aliased values in spreadsheets are not readable on this theme:

![unreadable_extreme_pro](https://user-images.githubusercontent.com/11302521/232462805-15f279be-2841-4548-9773-b6647a4a24f5.png)

To reproduce:
0. Get FreeCAD
1. Install ExtremeProDark from the addon manager
2. Make a new spreadsheet, insert a random value in a cell and then set an alias for it

CC @MisterMakerNL

**Comment by MisterMakerNL** [comment]
@Kreyren Did you restarted Freecad, since it is a theme color and not a stylesheet color it needs a reboot?
It also doesn't work if you only apply the stylesheet and not the theme.

**Comment by MisterMakerNL** [comment]
Please let me know if restarting was the issue for now I'll close it.

**Comment by Kreyren** [comment]
Sorry, i didn't get the notifications

I was applying just the stylesheet and not the theme, it seems to work now. Thanks for looking at it

I recommend adding the need to hit `Apply` in installation instructions
